### PR TITLE
Updated to handle blank datetime format variables

### PR DESCRIPTION
**Pull request by simplysiby**
Updated code to check and assign defaults if date and time formats are blank. Re-using the new variables to invoke ListCalendarEvents method.

### CODE REVIEW

**Comment by simplysiby** [comment]
@jasonjoh  : Thank you for considering the change. Would this auto update the code snippets in the tutorial ? I could not find a reference to the actual tutorial code snippets in git.

**Comment by x509cert** [comment]
I jsut hit the same issue in the code in the repo - I was going to fix the issue, but I saw this...

**Comment by jasonjoh** [comment]
I believe that code is referenced explicitly in one of the Markdown files. I'll check today and get this merged in.

**Comment by x509cert** [comment]
@jasonjoh FWIW, I just tested the code, and it works fine...

**Comment by jasonjoh** [comment]
@simplysiby I understand the change on lines 87 and 88, but the changes on 47-52 look like a longer form of the code that was already there. Was the old code not handling null/empty values properly?

**Comment by simplysiby** [comment]
Thanks @jasonjoh  @x509cert for merging/testing.

**Pull request merged**
